export const projectData = [
  {
    id: 1,
    title: 'Habits Dashboard',
    image: 'images/habitsdashboard.png',
    description: `Implemented the front end for a dashboard that allows users to curate a list of quantifiable habits and then track their progress using a calendar heatmap and a line graph.`,
    techStack: ['JSX', 'CSS', 'React', 'Redux', 'ChakraUI', 'Nivo'],
    demoLink: 'https://habitsdashboard.netlify.app/#',
    githubLink: 'https://github.com/Ahmed-O/HabitsDashboard',
  },
  {
    id: 2,
    title: 'Pokemon Memory Game',
    image: 'images/pokemon.png',
    description: `Programmed a memory card game where the user is tasked with matching pairs of Pokemon cards before the time limit expires. Implemented three levels of difficulty alongside background music that the user can toggle on or off.`,
    techStack: ['JSX', 'CSS', 'React', 'React Router v6', 'PokeAPI'],
    demoLink: 'https://pokemon-react-memory-game.netlify.app/',
    githubLink: 'https://github.com/Ahmed-O/pokemon-memory-game',
  },
  {
    id: 3,
    title: 'BluTube',
    image: 'images/blutube.png',
    description: `Implemented the UI for a Youtube clone using custom made React components. Allowed for search functionality using Youtube’s v3 data API.`,
    techStack: ['JSX', 'CSS', 'React', 'YouTube APIv3'],
    demoLink: 'https://ahmed-o.github.io/blutube/',
    githubLink: 'https://github.com/Ahmed-O/blutube',
  },
  {
    id: 4,
    title: 'PixPaint',
    image: 'images/pixpaint.png',
    description: `Developed a website that allows users to create pixel sketches or drawings on a grid canvas. Included a color picker, eraser, clear button and an option to change the size of the drawing grid.`,
    techStack: ['HTML', 'CSS', 'Javascript'],
    demoLink: 'https://ahmed-o.github.io/PixPaint/',
    githubLink: 'https://github.com/Ahmed-O/PixPaint',
  },
];